---
roles:
  - name: stefangweichinger.ansible_rclone
  - name: geerlingguy.docker
    version: 7.0.1

collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
  - name: community.docker
    version: 3.12.1
  - name: vladgh.samba