---
- name: Clone the btrfs-progs repository # noqa latest
  ansible.builtin.git:
    repo: git://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git
    dest: /tmp/btrfs-progs
    depth: 1

- name: Install required packages for building btrfs-progs
  ansible.builtin.package:
    name:
      - git
      - asciidoc
      - xmlto
      - uuid-dev
      - libattr1-dev
      - zlib1g-dev
      - libacl1-dev
      - e2fslibs-dev
      - libblkid-dev
      - liblzo2-dev
      - autoconf
      - automake
      - pkg-config
      - python3-sphinx
      - libzstd-dev
      - libudev-dev
    state: present

- name: Install sphinx_rtd_theme using pip (risky) # noqa command-instead-of-shell
  ansible.builtin.shell: pip install sphinx-rtd-theme --break-system-packages

- name: Remove older version of btrfs-tools
  ansible.builtin.package:
    name: btrfs-tools
    state: absent

- name: Run autogen.sh for btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: ./autogen.sh
    chdir: /tmp/btrfs-progs

- name: Configure btrfs-progs for building # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: ./configure
    chdir: /tmp/btrfs-progs

- name: Compile btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: make
    chdir: /tmp/btrfs-progs

- name: Install btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: make install
    chdir: /tmp/btrfs-progs

- name: Cleanup cloned repository
  ansible.builtin.file:
    path: /tmp/btrfs-progs
    state: absent

- name: Cleanup cloned repository
  ansible.builtin.file:
    path: /tmp/btrfs-progs
    state: absent
