---
- name: Clone the btrfs-progs repository # noqa latest
  ansible.builtin.git:
    repo: git://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git
    dest: /tmp/btrfs-progs
    depth: 1
  notify: Cleanup cloned repository

- name: Install required packages for building btrfs-progs
  ansible.builtin.package:
    name:
      - autoconf
      - automake
      - e2fslibs-dev
      - git
      - libacl1-dev
      - libattr1-dev
      - libblkid-dev
      - liblzo2-dev
      - libudev-dev
      - libzstd-dev
      - pkg-config
      - uuid-dev
      - zlib1g-dev
    state: present

- name: Remove older version of btrfs-tools
  ansible.builtin.package:
    name: btrfs-tools
    state: absent

- name: Run autogen.sh for btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: ./autogen.sh
    chdir: /tmp/btrfs-progs

- name: Configure btrfs-progs for building # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: ./configure --disable-documentation
    chdir: /tmp/btrfs-progs

- name: Compile btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: make
    chdir: /tmp/btrfs-progs

- name: Install btrfs-progs # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: make install
    chdir: /tmp/btrfs-progs
