---
- name: Set default value for update_needed
  ansible.builtin.set_fact:
    update_needed: false

- name: Check if btrfs-progs is installed
  ansible.builtin.command: btrfs --version
  register: installed_version
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Set update_needed to true if btrfs is not installed
  ansible.builtin.set_fact:
    update_needed: true
  when: installed_version.rc != 0

- name: Get latest release information from GitHub for btrfs-progs
  ansible.builtin.uri:
    url: https://api.github.com/repos/kdave/btrfs-progs/releases/latest
    return_content: true
  register: btrfs_github_release_page
  check_mode: false

- name: Set latest btrfs-progs version fact
  ansible.builtin.set_fact:
    btrfs_latest_version: "{{ btrfs_github_release_page.json.tag_name | regex_replace('^v', '') }}"

- name: Extract version number from installed version
  ansible.builtin.set_fact:
    installed_version_number: "{{ installed_version.stdout.split()[1] | regex_replace('^v', '') }}"
  when: installed_version.rc == 0

- name: Compare installed version with the latest version
  ansible.builtin.set_fact:
    update_needed: "{{ btrfs_latest_version is version(installed_version_number | default('0'), '>') }}"
  when: installed_version.rc == 0

- name: Debug installed_version_number
  ansible.builtin.debug:
    var: installed_version_number

- name: Debug btrfs_latest_version
  ansible.builtin.debug:
    var: btrfs_latest_version

- name: Include btrfs install
  ansible.builtin.include_tasks:
    file: install.yml
  when: update_needed
