---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: start and enable cache mover timer
  ansible.builtin.systemd:
    name: cache_mover.timer
    state: started
    enabled: true
