---
- name: Set permissions on media_cached
  ansible.builtin.file:
    path: "{{ media_cached }}"
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"

- name: Set permissions on media_noncached
  ansible.builtin.file:
    path: "{{ media_noncached }}"
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"
  when: not cache_disks_exist

- name: Set permissions on .snapshots directory for media_cached
  ansible.builtin.file:
    path: "{{ media_cached }}/.snapshots"
    owner: root
    group: root
    mode: "0770"
    recurse: true
  failed_when: false
  when: cache_disks_exist

- name: Set permissions on .snapshots directory for media_noncached
  ansible.builtin.file:
    path: "{{ media_noncached }}/.snapshots"
    owner: root
    group: root
    mode: "0770"
    recurse: true
  failed_when: false
  when: not cache_disks_exist
