---
- name: Set cache disk facts
  ansible.builtin.set_fact:
    cache_disks: "{{ cache_disks | default([]) }}"
    cache_disks_only: "{{ cache_disks | select('match', '^/dev/') | list }}"
    cache_paths_only: "{{ cache_disks | reject('match', '^/dev/') | list }}"

- name: Set cache_disks_exist fact
  ansible.builtin.set_fact:
    cache_disks_exist: "{{ (cache_disks_only + cache_paths_only) | length > 0 }}"

- name: Count the number of cache disks and paths
  ansible.builtin.set_fact:
    cache_disks_count: "{{ (cache_disks_only + cache_paths_only) | length }}"
  when: cache_disks_exist

- name: Count the number of data_disks
  ansible.builtin.set_fact:
    data_disks_count: "{{ data_disks | length }}"

- name: Generate data_mounts list
  ansible.builtin.set_fact:
    data_mounts: "{{ data_mounts | default([]) + ['/mnt/data-disks/data%02d' % (index + 1)] }}"
  loop: "{{ data_disks }}"
  loop_control:
    index_var: index

- name: Media_cached
  ansible.builtin.include_tasks:
    file: media_cached.yml
  when: cache_disks_exist

- name: Media_cold
  ansible.builtin.include_tasks:
    file: media_cold.yml
  when: cache_disks_exist

- name: Media_noncached
  ansible.builtin.include_tasks:
    file: media_noncached.yml
  when: not cache_disks_exist

- name: Create directories
  ansible.builtin.include_tasks:
    file: create_data_directories.yml

- name: Configure fuse
  ansible.builtin.include_tasks:
    file: configure_fuse.yml

- name: Configure mount perms
  ansible.builtin.include_tasks:
    file: configure_perms.yml

- name: Cleanup
  ansible.builtin.include_tasks:
    file: mergerfs_cleanup.yml
