---
- name: Ensure mountpoint for media exists
  ansible.builtin.file:
    path: "{{ media_noncached }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"

- name: Deploy mergerfs media_noncached systemd service
  ansible.builtin.template:
    src: mergerfs.mount.media_noncached.j2
    dest: /etc/systemd/system/mergerfs-media-noncached.service
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart mergerfs_media_noncached and ensure enabled
