---
- name: Ensure mountpoint for media-cold exists
  ansible.builtin.file:
    path: "{{ media_cold }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"

- name: Deploy mergerfs media_cold systemd service
  ansible.builtin.template:
    src: mergerfs.mount.media_cold.j2
    dest: /etc/systemd/system/mergerfs-media-cold.service
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart mergerfs_media_cold and ensure enabled
