---

- name: Remove mergerfs-media-cold and mergerfs-media-cache services (no cache disks or paths)
  when: cache_disks_exist is defined and not cache_disks_exist
  block:
    - name: Stop and disable unwanted services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - mergerfs-media-cold.service
        - mergerfs-media-cache.service
      ignore_errors: true

    - name: Remove unwanted services
      ansible.builtin.file:
        path: /etc/systemd/system/{{ item }}
        state: absent
      loop:
        - mergerfs-media-cold.service
        - mergerfs-media-cache.service
      notify:
        - Reload systemd daemon

- name: Remove mergerfs-cache-disks and mergerfs-cache-pool services (single cache disk or path)
  when: (cache_disks_only + cache_paths_only) | length == 1
  block:
    - name: Stop and disable unwanted services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - mergerfs-cache-disks.service
        - mergerfs-cache-pool.service
      ignore_errors: true

    - name: Remove unwanted services
      ansible.builtin.file:
        path: /etc/systemd/system/{{ item }}
        state: absent
      loop:
        - mergerfs-cache-disks.service
        - mergerfs-cache-pool.service
      notify:
        - Reload systemd daemon
      when: (cache_disks_only + cache_paths_only) | length == 1

- name: Remove mergerfs-media-noncached service (cache disks or paths exist)
  when: cache_disks_exist is defined and cache_disks_exist
  block:
    - name: Stop and disable unwanted mergerfs-media-noncached service
      ansible.builtin.systemd:
        name: mergerfs-media-noncached.service
        enabled: false
        state: stopped
      ignore_errors: true

    - name: Remove unwanted mergerfs-media-noncached service
      ansible.builtin.file:
        path: /etc/systemd/system/mergerfs-media-noncached.service
        state: absent
      notify:
        - Reload systemd daemon
