---
# scrutiny vars
scrutiny_image: "{% if scrutiny_mode == 'collector' %}ghcr.io/analogj/scrutiny:master-collector{% else %}ghcr.io/analogj/scrutiny:master-omnibus{% endif %}"

scrutiny_ports:
  - "{{ scrutiny_webui_port }}:8080"
  - 8086:8086
scrutiny_volumes:
  - "{{ scrutiny_config_path }}:/opt/scrutiny/config"
  - "{{ scrutiny_influxdb_path }}:/opt/scrutiny/influxdb"
  - "{{ scrutiny_config_file }}:/opt/scrutiny/config/scrutiny.yaml"
  - /run/udev:/run/udev:ro
  - /dev:/dev:ro
scrutiny_config_path: /opt/docker/scrutiny/data
scrutiny_config_file: /opt/docker/scrutiny/data/scrutiny.yaml
scrutiny_influxdb_path: /opt/docker/scrutiny/influxdb2
