---
- name: Stage Scrutiny
  ansible.builtin.include_tasks:
    file: stage.yml
  tags:
    - scrutiny

- name: Configure Notifications
  ansible.builtin.include_tasks:
    file: notify.yml
  when: scrutiny_mode != 'collector'
  tags:
    - scrutiny

- name: Deploy Scrutiny
  ansible.builtin.include_tasks:
    file: deploy.yml
  tags:
    - scrutiny
