---
- name: Set permissions on mount root directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "770"
  loop:
    - "{{ data_mount_path }}"
    - "{{ cache_mount_path }}"
    - "{{ parity_mount_path }}"

- name: Discover .snapshots directories
  ansible.builtin.stat:
    path: "{{ data_mount_path }}/data{{ '%02d' | format(item) }}/.snapshots"
  loop: "{{ range(1, data_disks_count | int + 1) | list }}"
  loop_control:
    loop_var: item
  register: snapshot_directory_check

- name: Set ownership and permissions on existing .snapshots directories
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    state: directory
    owner: root
    group: root
    mode: "0770"
  loop: "{{ snapshot_directory_check.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  when: item.stat.exists
