---
- name: Ensure base mount point exists
  ansible.builtin.file:
    path: /mnt/btrfs-root
    state: directory

- name: Ensure mount point directories exist
  ansible.builtin.file:
    path: "/mnt/btrfs-root/{{ item | basename }}"
    state: directory
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"

- name: Check if the filesystem is already mounted
  ansible.builtin.shell: |
    set -o pipefail
    mount | grep "/mnt/btrfs-root/{{ item | basename }}"
  args:
    executable: /bin/bash
  register: mount_check
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
  changed_when: false
  failed_when: false

- name: Mount the main Btrfs filesystem partition
  ansible.builtin.command:
    cmd: >
      mount -t btrfs
      {{ item if item not in partitioned_disks else item + '-part1' }}
      /mnt/btrfs-root/{{ item | basename }}
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
  when: mount_check.results | selectattr('rc', 'equalto', 1) | list | length > 0
  register: mount_result
  failed_when:
    - mount_result.rc != 0
    - "'already mounted' not in mount_result.stderr"

- name: List subvolumes
  ansible.builtin.shell: |
    set -o pipefail
    btrfs subvolume list /mnt/btrfs-root/{{ item | basename }} | grep data
  args:
    executable: /bin/bash
  loop: "{{ data_disks }}"
  register: subvolume_check
  changed_when: false
  failed_when: false

- name: Create Btrfs data subvolume
  ansible.builtin.command: >
    btrfs subvolume create /mnt/btrfs-root/{{ item.item | basename }}/data
  loop: "{{ subvolume_check.results }}"
  when: "'data' not in item.stdout"
  loop_control:
    label: "{{ item.item }}"
  register: create_subvolume_result
  failed_when:
    - create_subvolume_result.rc != 0
    - "'already exists' not in create_subvolume_result.stderr"

- name: Unmount the fs
  ansible.builtin.command: umount /mnt/btrfs-root/{{ item | basename }}
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
  register: unmount_result
  failed_when:
    - unmount_result.rc != 0
    - "'not mounted' not in unmount_result.stderr"

- name: Remove individual mount points
  ansible.builtin.file:
    path: "/mnt/btrfs-root/{{ item | basename }}"
    state: absent
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
