---
- name: Prepare disks
  ansible.builtin.include_tasks:
    file: prepare_disks.yml

- name: Configure Btrfs subvolumes
  ansible.builtin.include_tasks:
    file: configure_subvolumes.yml

- name: Configure Btrfs subvolume mounts
  ansible.builtin.include_tasks:
    file: configure_subvolume_mount.yml

- name: Configure/mount parity & cache disks
  ansible.builtin.include_tasks:
    file: configure_parity_cache.yml

- name: Set mount permissions
  ansible.builtin.include_tasks:
    file: configure_mount_perms.yml

- name: Cleanup orphaned mount points
  ansible.builtin.include_tasks:
    file: cleanup_orphaned_mounts.yml
