---

- name: Upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
