---

- name: Find latest release of fastfetch
  community.general.github_release:
    user: fastfetch-cli
    repo: fastfetch
    action: latest_release
  register: fastfetch_latest_release
  delegate_to: localhost
  run_once: true
  become: false
  when: fastfetch_version == 'latest'

- name: Set fastfetch latest version
  ansible.builtin.set_fact:
    fastfetch_version: "{{ fastfetch_latest_release.tag if fastfetch_version == 'latest' else fastfetch_version }}"

- name: Check fastfetch install state/version
  ansible.builtin.command: fastfetch --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: fastfetch_install_state

- name: Install/update Fastfetch
  when: >-
    fastfetch_install_state.rc != 0
    or fastfetch_install_state.stdout.split()[1] != fastfetch_version
  block:
    - name: Fail if architecture is not supported
      ansible.builtin.fail:
        msg: "Unsupported architecture: {{ ansible_architecture }}"
      when: fastfetch_architecture == "unknown"

    - name: Install Fastfetch
      ansible.builtin.apt:
        deb: https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_version }}/fastfetch-linux-{{ fastfetch_architecture }}.deb
        state: present
