---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users | map(attribute='groups') | flatten | unique }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: "{{ item.append | default(true) }}"
    create_home: "{{ item.create_home | default(false) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  loop: "{{ users }}"
