---
- name: Set default value for update_needed
  ansible.builtin.set_fact:
    update_needed: false

- name: Check if mergerfs is installed
  ansible.builtin.command: mergerfs --version
  register: installed_mergerfs_version
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Set update_needed to true if mergerfs is not installed
  ansible.builtin.set_fact:
    update_needed: true
  when: installed_mergerfs_version.rc != 0

- name: Get latest release information from GitHub for mergerfs
  ansible.builtin.uri:
    url: https://api.github.com/repos/trapexit/mergerfs/releases/latest
    return_content: true
  register: mergerfs_github_release_page
  check_mode: false

- name: Set latest mergerfs version fact
  ansible.builtin.set_fact:
    mergerfs_latest_version: "{{ mergerfs_github_release_page.json.tag_name | regex_replace('^v', '') }}"

- name: Extract version number from installed mergerfs version
  ansible.builtin.set_fact:
    installed_mergerfs_version_number: "{{ installed_mergerfs_version.stdout.split()[1] | regex_replace('^v', '') }}"
  when: installed_mergerfs_version.rc == 0

- name: Compare installed mergerfs version with the latest version
  ansible.builtin.set_fact:
    update_needed: "{{ mergerfs_latest_version != (installed_mergerfs_version_number | default('0')) }}"

- name: Debug installed_mergerfs_version_number
  ansible.builtin.debug:
    var: installed_mergerfs_version_number

- name: Debug mergerfs_latest_version
  ansible.builtin.debug:
    var: mergerfs_latest_version

- name: Install/update mergerfs
  when:
    - ansible_pkg_mgr == 'apt'
    - update_needed
  block:
    - name: Install xz-utils package for .deb package installation
      ansible.builtin.apt:
        name: xz-utils
        state: present
        update_cache: true

    - name: Install mergerfs package with apt
      ansible.builtin.apt:
        deb: >-
          https://github.com/trapexit/mergerfs/releases/download/{{
            mergerfs_latest_version + '/' + mergerfs_pkg_prefix + mergerfs_latest_version + mergerfs_pkg_suffix }}
        state: present
