---
- name: Ensure directories for snapraid.content files exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ user }}"
    group: root
    mode: "0755"
  loop: "{{ content_files }}"

- name: Generate SnapRAID configuration
  ansible.builtin.template:
    src: snapraid.j2
    dest: "{{ configure_snapraid_snapraid_config }}"
    owner: "{{ user }}"
    group: root
    mode: "0644"
