---
- name: Clone or update snapraid-btrfs repository # noqa latest
  ansible.builtin.git:
    repo: https://github.com/D34DC3N73R/snapraid-btrfs.git
    dest: /tmp/snapraid-btrfs
    update: true

- name: Copy snapraid-btrfs script to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/snapraid-btrfs/snapraid-btrfs
    dest: /usr/local/bin/snapraid-btrfs
    mode: "0755"
    remote_src: true

- name: Ensure snapraid-btrfs is executable
  ansible.builtin.file:
    path: /usr/local/bin/snapraid-btrfs
    mode: "0755"

- name: Verify snapraid-btrfs can see Snapper configs
  ansible.builtin.command:
    cmd: "{{ configure_snapraid_snapraid_btrfs_executable }} list"
  register: snapraid_btrfs_output
  changed_when: false
  failed_when: snapraid_btrfs_output.rc != 0 and "No snapper configs found" not in snapraid_btrfs_output.stderr
  check_mode: false

- name: Display snapraid-btrfs output
  ansible.builtin.debug:
    var: snapraid_btrfs_output.stdout_lines

# TODO: Remove this once the following PR is merged https://github.com/automorphism88/snapraid-btrfs/pull/34
- name: Patch snapraid-btrfs
  ansible.builtin.lineinfile:
    path: /usr/local/bin/snapraid-btrfs
    regexp: >-
      ^(\s{8})sed -e '/\^SUBVOLUME /!d' -e 's/\^SUBVOLUME\[ ]\*\| //'\)\"$
    line: >-
      \1sed -e '/^SUBVOLUME /!d' -e 's/^SUBVOLUME[ ]*[|│] //')"
    backrefs: true
