---
- name: Confirm disk wiping
  when: wipe_and_setup
  block:
    - name: Pause to confirm wipe and setup
      ansible.builtin.pause:
        prompt: |
          You have set wipe_and_setup to true. This will wipe all non-compliant data/parity/cache disk vars.
          Are you sure you want to continue? (yes/no)
      register: wipe_confirmation

    - name: Validate user input
      ansible.builtin.fail:
        msg: Invalid input. Please enter 'yes' or 'no'.
      when: wipe_confirmation.user_input not in ['yes', 'no']

    - name: Recap disk wiping confirmation
      ansible.builtin.debug:
        msg: You have confirmed to proceed with disk wiping. You will be prompted if/when disks need to be wiped.
      when: wipe_confirmation.user_input == 'yes'

    - name: Abort playbook if user does not confirm
      ansible.builtin.fail:
        msg: Disk wiping not confirmed. Aborting playbook execution.
      when: wipe_confirmation.user_input != 'yes'
